### ISSUE TITLE
Missing "data/MSRVTT/processing/raw-captions.pkl" 

### ISSUE THREAD

**Issue by e0lithic** [albanie/collaborative-experts#1]
While trying to replicate the results for msrvtt, the data loader for msvrtt requires the *"processing/raw-captions.pkl"* file which is not fetched as part of the features downloaded using the *"sync_experts.py"* script. Could you please clarify as to how to obtain the required  *"raw-captions.pkl"* file.

Thanks

**Comment by albanie** [comment]
@e0lithic, thanks for pointing this out.  Will push a fix shortly.

**Comment by albanie** [comment]
@e0lithic, have updated the tar files and pushed a fix.  Feel free to re-open if it still doesn't work for you. Thanks!
