### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by ppj567** [albanie/collaborative-experts#19]
Hi, I cannot download the config or model for TeachText results. It seems the files on the server are invalid now. Could you please update them or make available? 
Much appreciated.

**Comment by ioanacroi** [comment]
Hi,
Indeed the TeachText configs and models are not available at the moment. We will update them soon and let you know. Meanwhile, please note that the configs and models for the [original CE](https://github.com/albanie/collaborative-experts#collaborative-experts) are available right now.
Cheers,
Ioana

**Comment by ioanacroi** [comment]
Hi,

The TeachText configs and models are available now.

Cheers,
Ioana
