### ISSUE TITLE
Can not reproduce results on LSMDC dataset

### ISSUE THREAD

**Issue by ppj567** [albanie/collaborative-experts#23]
Hi, I am trying to reproduce the results of CE on LSMDC dataset. I follow the instructions to evaluate the [provided pre-trained model](http://www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/models/lsmdc-train-full-ce/b314166a/seed-0/2020-01-22_09-13-44/trained_model.pth) with [config](http://www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/models/msvd-train-full-ce/5bb8dda1/seed-0/2020-01-30_12-29-56/config.json) on LSMDC but get the results somehow lower than expected:
![image](https://user-images.githubusercontent.com/78494473/118399494-f9a74680-b68f-11eb-9ccd-8a95c49cabf5.png)

I evaluate it with the following script:
```
python test.py --config ./LSMDC_models/config.json --resume ./LSMDC_models/trained_model.pth --device 0 --eval_from_training_config
```
How could I reproduce the reported results below:
![image](https://user-images.githubusercontent.com/78494473/118399623-a2ee3c80-b690-11eb-94eb-599e90cd627a.png)

Many thanks!

**Comment by ioanacroi** [comment]
Hi,

Please be aware that all the numbers from the tables are reported over three seeded runs. The results you are obtaining are the exact numbers for the first seeded experiment. You can check the results of every seed in the [log](https://www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/log/lsmdc-train-full-ce/b314166a/seed-0/2020-01-22_09-13-44/summary-seed-0_seed-1_seed-2.json).

Cheers!
