### ISSUE TITLE
Testing model on different data

### ISSUE THREAD

**Issue by Tortoise17** [albanie/collaborative-experts#25]
Very nice / excellent effort. 
I have one question
Is it possible for test case to run any example videos with any of the models like v2t? because I tried to change the train_vid.txt list of videos and the videos inside folder. Apparently it didn't work. So, should I train my own model for any testing video? or?
As far as I have experienced, I think weights are saved for specific datasets with each model. 
Other question, could I fine-tune on my data-set? is it possible?
Please if you can comment and guide.

**Comment by ioanacroi** [comment]
Hi,

Are you interested in testing with a video that is not part of the datasets? If the answer is yes, then in order to test it you should first extract all the features for all the experts for that video.

Cheers,
Ioana

**Comment by Tortoise17** [comment]
@ioanacroi is there any workflow where I can extract features how you have done it here. Please if you can provide a piece of code?

**Comment by ioanacroi** [comment]
For more information please follow the conversation [here]( https://github.com/albanie/collaborative-experts/issues/3#issuecomment-537587654).
