### ISSUE TITLE
Fine tuning on different data

### ISSUE THREAD

**Issue by Tortoise17** [albanie/collaborative-experts#26]
Is it possible to take one trained engine and fine tune on other dataset?

**Comment by ioanacroi** [comment]
Hi,

It should be possible! If you use the exact same experts for both datasets then it should be straight-forward. Otherwise, you can still initialize some sub-parts of the model.

Cheers,
Ioana

**Comment by Tortoise17** [comment]
Thank you . If you can mention which files need to be changed and if the same trained experts can work on the change of the video files for fine tuning ? and any script to generate these experts (for fine tuning experts training) would be great help to reproduce the results for training of gated model.

**Comment by ioanacroi** [comment]
Regarding the feature extraction for new datasets please follow the conversation [here]( https://github.com/albanie/collaborative-experts/issues/3#issuecomment-537587654).

**Comment by Tortoise17** [comment]
@ioanacroi Yes I have seen but is there any working workflow instead manually each expert separately. maybe there is some tool which unites them

**Comment by Tortoise17** [comment]
@ioanacroi Export of experts under one umbrella. I mean that.

**Comment by Tortoise17** [comment]
> Regarding the feature extraction for new datasets please follow the conversation [here](https://github.com/albanie/collaborative-experts/issues/3#issuecomment-537587654).
`Yes I have seen but is there any working workflow instead manually each expert separately. maybe there is some tool which unites them. Export of experts under one umbrella. I mean that., `
