### ISSUE TITLE
TeachText experts features extraction and training experts !!

### ISSUE THREAD

**Issue by Tortoise17** [albanie/collaborative-experts#27]
Is there a single script example where one can extract the features for training for experts based on my own dataset for specially TEACHTEXT for all videos in a folder? 

like the features present in folders `structured_symlinks`. It seems they should be generated to start any training for gated model and for that a separate routine or code has to work.

**Comment by ioanacroi** [comment]
Hi,

Both for Collaborative Experts and TeachText we use various features which are extracted using the corresponding pretrained models. For more information please follow the conversation [here]( https://github.com/albanie/collaborative-experts/issues/3#issuecomment-537587654).

Cheers!
