### ISSUE TITLE
missing finetuned text features in MSRVTT (teachtext)

### ISSUE THREAD

**Issue by hooraid** [albanie/collaborative-experts#29]
I successfully reproduce your code (teachtext) but cannot on MSRVTT dataset, 
because"gpt2-xl-finetune.pkl" is missing. I hope to fix provided MSRVTT features. 
Also, "raw-captions.pkl" is missing too. (but I copy same file from old[CE] data)
Thanks

**Comment by Tortoise17** [comment]
@hooraid can you share the script? or have you tried on other dataset or random file / data?

**Comment by ioanacroi** [comment]
@hooraid Sorry for the inconvenience. We have updated the MSRVTT archive.
Cheers!

**Comment by hooraid** [comment]
> @hooraid can you share the script? or have you tried on other dataset or random file / data?

I just tried scripts from the repository. I did not try a custom dataset.
