### ISSUE TITLE
About raw text data

### ISSUE THREAD

**Issue by ezeli** [albanie/collaborative-experts#36]
Hi, thank you so much for such an excellent job!
Can you provide the raw text data (including objects, actions, speech, OCR, etc.) extracted from the MSRVTT dataset. Because [here](http:/www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/features-v2/MSRVTT-experts.tar.gz) seems to only contain feature data.
Thanks again!

**Comment by Tortoise17** [comment]
raw text is in pkl format available with each dataset. with MSRVTT also. See raw captions tile.

**Comment by ezeli** [comment]
raw-captions.pkl file contains only captions, no text data such as objects, actions, speech, OCR, etc.

**Comment by ioanacroi** [comment]
Hi,

We use only the feature data that is provided online. We do not use any raw text data for the used experts.

Cheers,
Ioana

**Comment by ezeli** [comment]
OK, thanks!
