### ISSUE TITLE
MSR-VTT dataset download link

### ISSUE THREAD

**Issue by AmeenAli** [albanie/collaborative-experts#6]
hello <br>
the download link provided for msrvtt dataset: http:/www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/features/MSRVTT-experts.tar.gz <br> is not available can you update the link? <br> thanks

**Comment by albanie** [comment]
Hi @AmeenAli, thanks! The link has been updated on the webpage. The features are now at http:/www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/features-v2/MSRVTT-experts.tar.gz
